-- Oracle XE 21c - Schema for Live Translator
-- Author: Bombowy
-- Created: 2025-10-16

-- Includes automatic demo user creation for testing purposes

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE translation_sessions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES users(id),
    source_lang VARCHAR2(10) NOT NULL,
    target_lang VARCHAR2(10) NOT NULL,
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP
);

CREATE TABLE translations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id NUMBER REFERENCES translation_sessions(id),
    input_text CLOB,
    translated_text CLOB,
    confidence NUMBER(5,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audio_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id NUMBER REFERENCES translation_sessions(id),
    original_audio BLOB,
    translated_audio BLOB,
    duration_ms NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



BEGIN
    INSERT INTO users (username)
    SELECT 'demo' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'demo');
    COMMIT;
END;